export const GET_ARTICLES = "GET_ARTICLES";
export const SET_ARTICLES = "SET_ARTICLES";
export const SELECT_ARTICLE = "SELECT_ARTICLE";
export const DESELECT_ARTICLE = "DESELET_ARTICLE";
export const SET_ERROR = "SET_ERROR";
export const START_LOADER = "START_LOADER";
